"""empty message

Revision ID: 14c10b18d7fe
Revises: c3b3262ce235
Create Date: 2024-06-09 07:50:01.607321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c10b18d7fe'
down_revision = 'c3b3262ce235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('author2', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('language')
        batch_op.drop_column('price')
        batch_op.drop_column('author2')
        batch_op.drop_column('author')
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###
