"""empty message

Revision ID: 21f13bc21054
Revises: 834b1a697901
Create Date: 2024-06-08 11:21:46.213511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f13bc21054'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.drop_index('ix_borrowed_book_book_id')

    op.drop_table('borrowed_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_book',
    sa.Column('bid', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('borrow_date', sa.VARCHAR(length=140), nullable=False),
    sa.Column('due_date', sa.VARCHAR(length=140), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('bid')
    )
    with op.batch_alter_table('borrowed_book', schema=None) as batch_op:
        batch_op.create_index('ix_borrowed_book_book_id', ['book_id'], unique=False)

    # ### end Alembic commands ###
